name: Test / MPEI Plugin

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - ready_for_review
    branches:
      - master

jobs:
  build:
    name: Extensions / Build
    runs-on: windows-2022
    steps:
      - name: Setup Visual Studio 2022
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 16.11

      - name: Git Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Build
        run: |
          build.cmd < nul
        working-directory: ${{ github.workspace }}\build
        shell: cmd

      - name: Upload Artifact / Plugin
        uses: actions/upload-artifact@v4
        if: ${{ success() }}
        with:
          name: ExtensionsPlugin
          path: |
            ${{ github.workspace }}\mpei-plugin\MPEIPlugin\bin\Release\MPEIPlugin.dll
          retention-days: 7
          if-no-files-found: error

  ci-status:
    name: Build Status
    runs-on: ubuntu-latest
    needs:
      - build
    if: always()
    steps:
      - name: Success
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failure
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
